In [4]:
#hello this is Pandas

In [10]:
import pandas as pd

In [7]:
data={"Name":["Hardik","Nishchal","Navik","Sarthya","Kartik"],
     "course":["CSAM","AIML","B.COM","IT","CSE"],
      "roll no.": [352,112,420,234,520],
      "Address": ["Shalimar Garden","Shalimar Garden","DLF","Mayur Vihar","Brij Vihar"]
     }

In [11]:
 df=pd.DataFrame(data)

In [12]:
print(df)

       Name course  roll no.          Address
0    Hardik   CSAM       352  Shalimar Garden
1  Nishchal   AIML       112  Shalimar Garden
2     Navik  B.COM       420              DLF
3   Sarthya     IT       234      Mayur Vihar
4    Kartik    CSE       520       Brij Vihar

In [14]:
ser=pd.Series(data)

In [15]:
 print(ser)

Name               [Hardik, Nishchal, Navik, Sarthya, Kartik]
course                           [CSAM, AIML, B.COM, IT, CSE]
roll no.                            [352, 112, 420, 234, 520]
Address     [Shalimar Garden, Shalimar Garden, DLF, Mayur ...
dtype: object

In [19]:
pd.Series(data,index=["a","b","c","d","e"])

a    NaN
b    NaN
c    NaN
d    NaN
e    NaN
dtype: object

In [21]:
df.drop("Address",axis=1)

       Name course  roll no.
0    Hardik   CSAM       352
1  Nishchal   AIML       112
2     Navik  B.COM       420
3   Sarthya     IT       234
4    Kartik    CSE       520

In [22]:
df.drop(0)

       Name course  roll no.          Address
1  Nishchal   AIML       112  Shalimar Garden
2     Navik  B.COM       420              DLF
3   Sarthya     IT       234      Mayur Vihar
4    Kartik    CSE       520       Brij Vihar

In [23]:
print(df)

       Name course  roll no.          Address
0    Hardik   CSAM       352  Shalimar Garden
1  Nishchal   AIML       112  Shalimar Garden
2     Navik  B.COM       420              DLF
3   Sarthya     IT       234      Mayur Vihar
4    Kartik    CSE       520       Brij Vihar

In [28]:
df["Name"]

0      Hardik
1    Nishchal
2       Navik
3     Sarthya
4      Kartik
Name: Name, dtype: object

In [29]:
df["Address"]

0    Shalimar Garden
1    Shalimar Garden
2                DLF
3        Mayur Vihar
4         Brij Vihar
Name: Address, dtype: object

In [31]:
df["CGPA"] = [9.2,9,9.1,9.2,9.3]

In [32]:
df

       Name course  roll no.          Address  CGPA
0    Hardik   CSAM       352  Shalimar Garden   9.2
1  Nishchal   AIML       112  Shalimar Garden   9.0
2     Navik  B.COM       420              DLF   9.1
3   Sarthya     IT       234      Mayur Vihar   9.2
4    Kartik    CSE       520       Brij Vihar   9.3

In [33]:
df.drop("CGPA")

KeyError: "['CGPA'] not found in axis"

In [34]:
df.drop("CGPA",axis=1)

       Name course  roll no.          Address
0    Hardik   CSAM       352  Shalimar Garden
1  Nishchal   AIML       112  Shalimar Garden
2     Navik  B.COM       420              DLF
3   Sarthya     IT       234      Mayur Vihar
4    Kartik    CSE       520       Brij Vihar

In [35]:
df.drop("Address",axis=1,inplace=True)

In [36]:
df

       Name course  roll no.  CGPA
0    Hardik   CSAM       352   9.2
1  Nishchal   AIML       112   9.0
2     Navik  B.COM       420   9.1
3   Sarthya     IT       234   9.2
4    Kartik    CSE       520   9.3

In [39]:
df[["Name","course","roll no."]]

       Name course  roll no.
0    Hardik   CSAM       352
1  Nishchal   AIML       112
2     Navik  B.COM       420
3   Sarthya     IT       234
4    Kartik    CSE       520

In [40]:
df.loc[0]

Name        Hardik
course        CSAM
roll no.       352
CGPA           9.2
Name: 0, dtype: object

In [42]:
df.loc[[0,1]]

       Name course  roll no.  CGPA
0    Hardik   CSAM       352   9.2
1  Nishchal   AIML       112   9.0

In [43]:
df

       Name course  roll no.  CGPA
0    Hardik   CSAM       352   9.2
1  Nishchal   AIML       112   9.0
2     Navik  B.COM       420   9.1
3   Sarthya     IT       234   9.2
4    Kartik    CSE       520   9.3

In [44]:
df.loc[[2,3,4]][["course","roll no.","CGPA"]]

  course  roll no.  CGPA
2  B.COM       420   9.1
3     IT       234   9.2
4    CSE       520   9.3